- name: 安装docker-ce、docker-compose
  shell: "curl -sSL https://get.docker.com/ | sh &&\
        yum install python-pip -y
        pip install -U docker-compose"

- name: 配置docker.service相关参数
  template: src=docker.service.j2 dest=/usr/lib/systemd/system/docker.service

- name: 配置daemon.json相关参数
  template: src=daemon.json.j2 dest=/etc/docker/daemon.json
  when: DOCKER_INSECURE_REGISTRIES != ''

- name: 重启docker加载配置
  shell: 'systemctl daemon-reload && systemctl restart docker'
